import type { Metadata } from "next";

import {
  MAGIC_TEXT,
  MAX_LABEL_BYTES,
  MAX_SCRIPT_BYTES,
  PROTOCOL_VERSION,
  RADIANT_MAINNET,
  encodeHashMarkScript,
  bytesToHex,
  supportedAlgorithms,
} from "@hashmark/protocol";

export const metadata: Metadata = {
  title: "Protocol",
  description:
    "The HashMark on-chain format: byte layout, validation rules and how to write your own verifier.",
};

/**
 * The human-readable protocol page.
 *
 * The example is **generated by the encoder at build time**, not typed into the
 * page. A documented format that has drifted from its implementation is worse
 * than no documentation, and this makes drift impossible.
 */
const EXAMPLE_DIGEST =
  "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08";
const EXAMPLE_LABEL = "Contract draft";
/**
 * Stand-in attestation bytes for the example.
 *
 * A real record's signer and signature come from a wallet; the page only needs
 * something correctly shaped, and inventing them here is honest in a way that
 * pasting a real signature would not be — a signature copied out of a live mark
 * would verify against that mark, not this example.
 */
const EXAMPLE_SIGNER = "26ba056431ec69cf27eabeaab250d99ddbd895d2";
const EXAMPLE_SIGNATURE = "1f" + "ab".repeat(64);
const EXAMPLE_SCRIPT = bytesToHex(
  encodeHashMarkScript({
    algorithm: "sha256",
    digest: EXAMPLE_DIGEST,
    label: EXAMPLE_LABEL,
    signerHash160: EXAMPLE_SIGNER,
    signature: EXAMPLE_SIGNATURE,
  }),
);
const MINIMAL_SCRIPT = bytesToHex(
  encodeHashMarkScript({
    algorithm: "sha256",
    digest: EXAMPLE_DIGEST,
    signerHash160: EXAMPLE_SIGNER,
    signature: EXAMPLE_SIGNATURE,
  }),
);

export default function ProtocolPage() {
  return (
    <div className="mx-auto max-w-3xl px-5 py-14 sm:py-20">
      <h1 className="font-display text-2xl font-semibold tracking-tight text-text sm:text-3xl">
        The HashMark protocol
      </h1>
      <p className="mt-4 text-base leading-relaxed text-muted">
        Version {PROTOCOL_VERSION}. A HashMark is a small, fixed record written
        into a Radiant transaction output. The format is public and documented so
        that anyone can write a verifier — you never have to trust this site to
        check a mark.
      </p>

      <Section title="Where a mark lives">
        <p>
          A HashMark is an <Code>OP_RETURN</Code> output carrying zero photons.
          An <Code>OP_RETURN</Code> output cannot be spent, so the record is
          inert: it holds no value and no one can move it.
        </p>
        <p>
          It is conventionally output 0, but a verifier should never assume that
          — scan every output, and address a specific one by index when
          following a receipt.
        </p>
      </Section>

      <Section title="The record">
        <p>
          Four pieces, in a fixed order, with no delimiters. The fourth is
          optional.
        </p>
        <div className="mt-4 overflow-x-auto rounded-lg border border-line bg-surface">
          <table className="w-full text-left text-sm">
            <thead>
              <tr className="border-b border-line">
                <th className="eyebrow px-4 py-3 font-medium">Field</th>
                <th className="eyebrow px-4 py-3 font-medium">Size</th>
                <th className="eyebrow px-4 py-3 font-medium">Value</th>
              </tr>
            </thead>
            <tbody className="text-muted">
              <Field name="Magic" size="8 bytes" value={`ASCII "${MAGIC_TEXT}"`} />
              <Field
                name="Header"
                size="2 bytes"
                value="version, then algorithm id"
              />
              <Field
                name="Digest"
                size="32 bytes"
                value="length fixed by the algorithm id"
              />
              <Field
                name="Label"
                size={`0–${MAX_LABEL_BYTES} bytes`}
                value="optional, UTF-8, no control characters"
              />
            </tbody>
          </table>
        </div>
        <p className="mt-4">
          Every push is minimally encoded, so a record has exactly one valid
          form. Two encoders given the same input produce identical bytes, which
          is what lets records be compared byte for byte.
        </p>
      </Section>

      <Section title="Hash algorithms">
        <div className="mt-4 overflow-hidden rounded-lg border border-line bg-surface">
          <table className="w-full text-left text-sm">
            <thead>
              <tr className="border-b border-line">
                <th className="eyebrow px-4 py-3 font-medium">Id</th>
                <th className="eyebrow px-4 py-3 font-medium">Name</th>
                <th className="eyebrow px-4 py-3 font-medium">Digest length</th>
              </tr>
            </thead>
            <tbody className="text-muted">
              {supportedAlgorithms().map((algorithm) => (
                <tr key={algorithm.id} className="border-b border-line last:border-0">
                  <td className="digest px-4 py-3 text-text">
                    0x{algorithm.id.toString(16).padStart(2, "0")}
                  </td>
                  <td className="digest px-4 py-3 text-text">{algorithm.name}</td>
                  <td className="px-4 py-3">{algorithm.digestLength} bytes</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <p className="mt-4">
          The algorithm is a field, not an assumption. A verifier reads it and
          derives the expected digest length from it, and reports an id it does
          not recognise rather than guessing. Adding an algorithm does not need a
          new protocol version.
        </p>
      </Section>

      <Section title="A real example">
        <p>
          This is generated by the same encoder the application uses, so it
          cannot drift from the implementation.
        </p>

        <p className="eyebrow mt-6 mb-2">With a label &ldquo;{EXAMPLE_LABEL}&rdquo;</p>
        <pre
          tabIndex={0}
          role="region"
          aria-label="Encoded HashMark record"
          className="digest overflow-x-auto rounded-lg border border-line bg-surface p-4 text-xs leading-relaxed text-text"
        >
          {EXAMPLE_SCRIPT}
        </pre>
        <p className="mt-2 text-xs text-faint">
          {EXAMPLE_SCRIPT.length / 2} bytes
        </p>

        <p className="eyebrow mt-6 mb-2">Without a label</p>
        <pre
          tabIndex={0}
          role="region"
          aria-label="Encoded HashMark record"
          className="digest overflow-x-auto rounded-lg border border-line bg-surface p-4 text-xs leading-relaxed text-text"
        >
          {MINIMAL_SCRIPT}
        </pre>
        <p className="mt-2 text-xs text-faint">
          {MINIMAL_SCRIPT.length / 2} bytes. The largest a record can be is{" "}
          {MAX_SCRIPT_BYTES} bytes, which keeps it relayable on any Radiant node.
        </p>
      </Section>

      <Section title="Reading one yourself">
        <p>
          You need no HashMark code and no Radiant library — just a node and
          about sixty lines in any language.
        </p>
        <ol className="mt-3 list-decimal space-y-2 pl-5">
          <li>
            Connect to any ElectrumX server speaking protocol 1.4 and check{" "}
            <Code>server.features</Code> reports the genesis hash{" "}
            <span className="digest break-all text-xs text-text">
              {RADIANT_MAINNET.genesisHash}
            </span>
            , so you know you are on the right chain.
          </li>
          <li>
            Call{" "}
            <Code>blockchain.transaction.get(txid, true)</Code> and take{" "}
            <Code>vout[n].scriptPubKey.hex</Code>.
          </li>
          <li>Check the first byte is <Code>0x6a</Code>, then read the pushes.</li>
          <li>
            Confirm the first push is <Code>{MAGIC_TEXT}</Code>, read the version
            and algorithm, and check the digest is the right length.
          </li>
          <li>Hash the file and compare.</li>
          <li>
            Read <Code>confirmations</Code> and <Code>blocktime</Code> from the
            same response for the timestamp.
          </li>
        </ol>
        <p className="mt-4">
          The full specification, including the threat model, every validation
          rule, and a reference parser, is in{" "}
          <Code>HASHMARK_PROTOCOL.md</Code> in the source repository.
        </p>
      </Section>

      <Section title="What a mark does not prove">
        <p>
          It shows that someone knew a file&rsquo;s fingerprint no later than the
          block that recorded it. It does not show who wrote the file, who owns
          it, whether anything in it is true, or that it is new — a mark sets the
          latest possible date, never the earliest.
        </p>
        <p>
          Block timestamps are set by miners and are accurate to roughly an hour,
          so read a mark&rsquo;s time as an upper bound rather than a precise
          moment.
        </p>
      </Section>
    </div>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-10">
      <h2 className="font-display text-base font-semibold text-text">{title}</h2>
      <div className="mt-3 space-y-3 text-sm leading-relaxed text-muted">
        {children}
      </div>
    </section>
  );
}

function Field({
  name,
  size,
  value,
}: {
  name: string;
  size: string;
  value: string;
}) {
  return (
    <tr className="border-b border-line last:border-0">
      <td className="px-4 py-3 text-text">{name}</td>
      <td className="px-4 py-3">{size}</td>
      <td className="px-4 py-3">{value}</td>
    </tr>
  );
}

function Code({ children }: { children: React.ReactNode }) {
  return (
    <code className="digest rounded bg-raised px-1.5 py-0.5 text-xs text-text">
      {children}
    </code>
  );
}
