/**
 * The shipped header-tree checkpoint: the anchor for every inclusion proof.
 *
 * A root over every block header from genesis to `height`. Any header at or
 * below that height is proved against it with a ~20-hash branch, and that
 * proof never ages: the archive of older marks, which is what anyone relies
 * on, is covered forever by whatever checkpoint a build happens to carry.
 * Marks newer than the checkpoint fall back to disclosing the server's word,
 * exactly as before, until a later build moves the floor up.
 *
 * HOW THIS VALUE WAS MADE is the trust decision, so it is recorded here:
 * generated by scripts/gen-checkpoint.ts, which takes the root from the
 * primary server and requires byte-identical agreement from servers run by
 * other operators, then proves a real mainnet mark against it with the same
 * code the application runs. A disagreement or a failed self-check prints
 * nothing.
 *
 * Generated 2026-10-02 at height 469251, corroborated by
 * electrumx.radiantcore.org and electrumx.radiant4people.com (independent
 * operators) and electrumx-eu.rxd-radiant.com.
 *
 * Do NOT fetch a replacement at runtime. Anything fetched may corroborate;
 * nothing fetched may anchor (HASHMARK_PROTOCOL.md §2.3.2). This constant is
 * trusted because it ships in the same reviewed artifact as the code that uses
 * it, and a substitute from elsewhere would not be.
 *
 * Do NOT coordinate it with other implementations. Independently generated
 * anchors are what would detect one of them being fed a false chain.
 */
export const HEADER_CHECKPOINT = {
  height: 469251,
  /** Display order, as ElectrumX returns it. */
  root: "f70c0f6cce3c783a6d9d244e5ef73454a07e62af5d503f2684337d32cacf9010",
} as const;
